### PR TITLE
#24: Fix timeout on GitHub actions

### LINKED ISSUE #24: Read timeout when waiting for Lambda to finish
Creating 1,000,000 files fails when running in a GitHub action:

```
2023-04-28 09:56:43.350 [INFO   ] Starting test S3DocumentFilesAdapterIT.testManySmallJsonFiles(TestInfo)... 
2023-04-28 09:56:45.162 [INFO   ] Actual setup TestSetupDescription [hashOfLambdaFunction=d9d6bb2e44c20a2cf1d9c5a8027f970e396c95367e4b4f13da1d0c75bf6ec8a6, numberOfFiles=1000000] does not match requested configuration TestSetupDescription [hashOfLambdaFunction=efac338ae0dd4bf9da2e6715b82f25d1c0c5c82aa83d316c981edae686492a5e, numberOfFiles=1000000] 
2023-04-28 09:56:45.838 [INFO   ] Creating role 'create-json-files-1682675805836-role'... 
2023-04-28 09:56:46.747 [INFO   ] Waiting PT30S for role 'create-json-files-1682675805836-role' being fully created... 
2023-04-28 09:57:17.912 [INFO   ] Waiting PT5S for lambda 'create-json-files-1682675805836' being fully created... 
2023-04-28 09:57:22.913 [INFO   ] Deleting small-json-files test setup from bucket persistent-small-json-files-test-fixture... 
2023-04-28 10:15:13.926 [INFO   ] Delete done in PT17M51.012603S 
2023-04-28 10:15:13.929 [INFO   ] Creating 1,000,000 files using 50 lambda functions in bucket persistent-small-json-files-test-fixture... 
2023-04-28 10:44:49.015 [SEVERE ] Lambda #29 {"bucket":"persistent-small-json-files-test-fixture","offset":580000,"numberOfFiles":20000,"prefix":"test-data-","action":"create"} failed :software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause. If this is a streaming operation, validate that data is being read or written in a timely manner. Channel Information: ChannelDiagnostics(channel=[id: 0xd6feb7c3, L:/10.1.0.39:44348 - R:lambda.eu-central-1.amazonaws.com/3.121.178.242:443], channelAge=PT4M31.196378S, requestCount=1) 
...
 2023-04-28 10:51:46.420 [SEVERE ] Lambda #49 {"bucket":"persistent-small-json-files-test-fixture","offset":980000,"numberOfFiles":20000,"prefix":"test-data-","action":"create"} failed :software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Read timed out 
2023-04-28 10:51:46.459 [SEVERE ] Lambda #41 {"bucket":"persistent-small-json-files-test-fixture","offset":820000,"numberOfFiles":20000,"prefix":"test-data-","action":"create"} failed :software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Read timed out 
2023-04-28 10:51:46.685 [SEVERE ] Lambda #16 {"bucket":"persistent-small-json-files-test-fixture","offset":320000,"numberOfFiles":20000,"prefix":"test-data-","action":"create"} failed :software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause. If this is a streaming operation, validate that data is being read or written in a timely manner. Channel Information: ChannelDiagnostics(channel=[id: 0xf12c8c70, L:/10.1.0.39:48326 - R:lambda.eu-central-1.amazonaws.com/3.121.179.234:443], channelAge=PT4M31.603114S, requestCount=1) 
...
2023-04-28 10:51:46.887 [SEVERE ] Lambda #26 {"bucket":"persistent-small-json-files-test-fixture","offset":520000,"numberOfFiles":20000,"prefix":"test-data-","action":"create"} failed :software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause. If this is a streaming operation, validate that data is being read or written in a timely manner. Channel Information: ChannelDiagnostics(channel=[id: 0x9e7a13e1, L:/10.1.0.39:48402 - R:lambda.eu-central-1.amazonaws.com/3.121.179.234:443], channelAge=PT4M31.628093S, requestCount=1) 
2023-04-28 10:51:47.324 [SEVERE ] Lambda #1 {"bucket":"persistent-small-json-files-test-fixture","offset":20000,"numberOfFiles":20000,"prefix":"test-data-","action":"create"} failed :software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Read timed out 
...
2023-04-28 11:03:15.478 [SEVERE ] Lambda #9 {"bucket":"persistent-small-json-files-test-fixture","offset":180000,"numberOfFiles":20000,"prefix":"test-data-","action":"create"} failed :software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Read timed out 

Error:  com.exasol.adapter.document.files.S3DocumentFilesAdapterIT.testManySmallJsonFiles(TestInfo)  Time elapsed: 3,994.43 s  <<< ERROR!
java.lang.IllegalStateException: One or more lambda functions failed.
	at com.exasol.smalljsonfilesfixture.S3TestSetupLambdaController.waitForLambdasToFinish(S3TestSetupLambdaController.java:279)
	at com.exasol.smalljsonfilesfixture.S3TestSetupLambdaController.runLambdas(S3TestSetupLambdaController.java:248)
	at com.exasol.smalljsonfilesfixture.S3TestSetupLambdaController.createFiles(S3TestSetupLambdaController.java:95)
	at com.exasol.smalljsonfilesfixture.SmallJsonFilesTestSetup.setup(SmallJsonFilesTestSetup.java:45)
	at com.exasol.adapter.document.files.S3DocumentFilesAdapterIT.createTestSetupWithSmallJsonFiles(S3DocumentFilesAdapterIT.java:217)
	at com.exasol.adapter.document.files.S3DocumentFilesAdapterIT.testManySmallJsonFiles(S3DocumentFilesAdapterIT.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:98)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:503)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:475)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more
Caused by: io.netty.handler.timeout.ReadTimeoutException
```

See complete log at https://github.com/exasol/s3-document-files-virtual-schema/actions/runs/4828138085/jobs/8602023931

### Workaround
Run the following code locally:

```java
        final int count = 1_000_000;
        final int countPerLambda = 20_000;
        new SmallJsonFilesTestSetup().setup(Map.of("exa:project", "<project>", "exa:owner", "<email>"),
                "<bucket>", ProfileCredentialsProvider.create("<AWS account>"), count,
                countPerLambda);
```

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #24

### CODE REVIEW

**Review by ckunki — DISMISSED** [review]

File: src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js [hunk 1]
```diff
@@ -1,47 +1,49 @@
...
  * @typedef {Event & { bucket: string }} DeleteAllEvent
+ * @typedef {Event & { bucket: string, objects: string[] }} DeleteListEvent
+ * @typedef {import('@aws-sdk/client-s3')._Object} S3Object
  */
 
 /** Action for creating JSON files */
 const ACTION_CREATE = 'create';
 /** Action for deleting all objects from a bucket */
 const ACTION_DELETE_ALL = 'delete';
+/** Action for deleting a list of objects from a bucket */
```
Comment (ckunki) [inline src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js]: Proposal: Describe delete strategy:
1. delete all files (`ACTION_DELETE_ALL `), e.g. 1 e6 files 
2. invoke multiple lambda instances, each deleting a subset, e.g. 20 000 files (`ACTION_DELETE_LIST`) 
3. each lambda instance deletes 20 000 files in chunks of 1000 files (see `MAX_COUNT_PER_DELETE_REQUEST`)

Rationale: ...

File: src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js [hunk 2]
```diff
@@ -98,57 +95,142 @@ async function handleCreate(event, context) {
...
+        result.push(chunk);
+    }
+    return result;
+}
+
+/**
+ * Fetch all S3 objects from a bucket.
+ * @param {string} bucket the S3 bucket
+ * @returns {Promise<string[]>} the keys of all objects
+ */
```
Comment (ckunki) [inline src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js]: Could we rename the function to `listS3BucketContents()` or `listContents()` if you prefer.
And add some content that this is required (or "used") for deleting the objects, i.e. empty the bucket?

Comment (ckunki) [reply src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js]: Is it required to use the term "object" here? Aren't the contents of a bucket rather "files"? Or could it be something else as well?

File: src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js [hunk 3]
```diff
@@ -98,57 +95,142 @@ async function handleCreate(event, context) {
...
+async function handleDeleteList(event, context) {
+    /** @type {Promise<unknown>[]} */
+    const promises = [];
+    const chunks = splitIntoChunks(event.objects, MAX_COUNT_PER_DELETE_REQUEST);
+    console.log(`Deleting ${event.objects.length} objects in ${chunks.length}...`);
+    for (const chunk of chunks) {
+        const objectIdentifiers = chunk.map(key => { return { Key: key }; });
+        const command = new DeleteObjectsCommand({ Bucket: event.bucket, Delete: { Objects: objectIdentifiers } });
+        promises.push(doWithRetry(`Delete ${chunk.length} files`, () => s3.send(command)));
```
Comment (ckunki) [inline src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js:245]: Ah! here it is "files" 🙂

File: src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js [hunk 4]
```diff
@@ -98,57 +95,142 @@ async function handleCreate(event, context) {
...
+ * @param {Context} context the lambda context
+ */
+async function handleDeleteList(event, context) {
+    /** @type {Promise<unknown>[]} */
+    const promises = [];
+    const chunks = splitIntoChunks(event.objects, MAX_COUNT_PER_DELETE_REQUEST);
+    console.log(`Deleting ${event.objects.length} objects in ${chunks.length}...`);
+    for (const chunk of chunks) {
+        const objectIdentifiers = chunk.map(key => { return { Key: key }; });
+        const command = new DeleteObjectsCommand({ Bucket: event.bucket, Delete: { Objects: objectIdentifiers } });
```
Comment (ckunki) [inline src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js]: Here it is "objects", afaik part of the API, right?
So we cannot rename this. 🙁

Comment (ckunki) [reply src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js]: But in the end of the line it is "identifiers" then. In some other places it's "keys". 
I don't want to spread too much confusion and also not too much additional work.
But I'd love to have the terminology a little bit unified, cleaned up and as precise as possible.

**Review by ckunki — CHANGES_REQUESTED** [review]

File: README.md [hunk 5]
```diff
@@ -47,6 +47,31 @@ Currently only region `eu-central-1` is supported.
 
 Creating 1,000,000 S3 objects costs about $5. Compared to that storage is cheap, since the files are so small.
 
+## Architecture
+
+Creating and deleting many small files in S3 requires many HTTP requests. To reduce network latency for single requests and therefore speed up execution time we execute the requests for creating and deleting in an AWS Lambda. That's why we split the code into the client library written in Java and lambda code written in JavaScript.
```
Comment (ckunki) [inline README.md]:
```suggestion
Creating and deleting many small files in S3 requires many HTTP requests. To reduce network latency for each request and by that speed up the execution the requests for creating and deleting are executed in an AWS Lambda. The controlling code is therefore split into a client library written in Java and lambda code written in JavaScript.
```

File: README.md [hunk 6]
```diff
@@ -47,6 +47,31 @@ Currently only region `eu-central-1` is supported.
...
+
+### Deleting Files
+
+The time required for deleting files is dominated by the time to list all files in S3 as listing only returns 1,000 files at a time. That's why the Java code calls the lambda with request action type `delete`. The lambda lists all files, collects the file names and once 50,000 files are found, invokes another instance of itself with request action type `deleteList`, passing the files. This way listing and deleting can run in parallel.
```
Comment (ckunki) [inline README.md]:
```suggestion
The time required for deleting files is dominated by the time to list all files in S3 as listing only returns 1,000 files at a time. The Java code therefore needs to call the parent instance of the lambda with request action type `delete` multiple times. 

The parent lambda 
* lists all files
* collects the file names and 
* once 50,000 files are found, invokes a child instance of itself with request action type `deleteList`, passing the files. 

This way listing and deleting can run in parallel.
```

File: README.md [hunk 7]
```diff
@@ -47,6 +47,31 @@ Currently only region `eu-central-1` is supported.
...
+
+Please note that using this approach we can only delete around 1,100,000 files before hitting the lambda execution limit of 15 minutes.
```
Comment (ckunki) [inline README.md]:
```suggestion
Please note that using this approach we can only delete around 1,100,000 files before hitting the execution limit of 15 minutes for the root instance of the lambda function.
```

File: README.md [hunk 8]
```diff
@@ -47,6 +47,31 @@ Currently only region `eu-central-1` is supported.
...
+* When invoking too many lambdas in parallel (around 100) they will send too many requests in a short time to S3. Some of these requests will then fail with error `SlowDown: Please reduce your request rate`. 50 parallel invocations (i.e. 20,000 files per lambda) seem to be OK.
+  * The recommended solution to use a random hash in the file name to allow S3 partitioning didn't work.
+* We want to invoke Lambdas synchronously so that we know when they are done. In order to avoid HTTP request timeouts we increased the read timeout for the S3 library's HTTP client to more than 15 minutes. This works, but recently these long running HTTP request (20,000 files per lambda) started to fail with a read timeout on GitHub Actions, see issue [#24](https://github.com/exasol/small-json-files-test-fixture/issues/24). Reducing the number of files per lambda to 5,000 reduces the runtime sufficiently to avoid these timeouts.
+
+To solve these constraints we use a fixed thread pool for synchronously invoking the lambdas. This way only a limited number of lambdas is running concurrently. Experiments showed that a concurrency of 75 works well.
```
Comment (ckunki) [inline README.md]:
```suggestion
* AWS Lambdas have a maximum runtime of 15 minutes, so we can't create all files in a single lambda. 
* The number of concurrent requests to S3 is limited. When invoking too many lambdas in parallel, S3 causes a failure with error  `SlowDown: Please reduce your request rate`. 
* The recommended solution to use a random hash in the file name to allow S3 partitioning didn't work.

SJFTF uses the following approach: 
* The Java client invokes the Lambdas synchronously so that he knows when they are done. 
* Additionally the client increases the read timeout for the S3 library's HTTP client to more than 15 minutes. 
* Each lambda creates only 5 000 files to avoid a timeout for the HTTP request observed by the GitHub Action, see issue [#24](https://github.com/exasol/small-json-files-test-fixture/issues/24). 
The Java client uses a thread pool to limit the max. number of concurrent lambdas to 75.
```

**Review by ckunki — CHANGES_REQUESTED** [review]

**Review by ckunki — APPROVED** [review]
